language: php
php:
  - 5.5
  - 5.4
  - 5.3
before_script:
  - composer install
  - mysql -e "DROP DATABASE IF EXISTS b8_test;" -uroot
  - mysql -e "CREATE DATABASE b8_test;" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON b8_test.* TO b8_test@'localhost' IDENTIFIED BY 'b8_test'" -uroot
script: phpunit ./tests/