<ul class="nav nav-tabs">
    <?php $i = 0; foreach ($childFields as $key => $field): $i++; ?>
        <li class="<?= ($i == 1) ? 'active' : '' ?>"><a data-toggle="tab" href="#tab-<?= $field->getName(); ?>-<?= $key; ?>"><?= $field->getLabel(); ?></a></li>
    <?php endforeach; ?>
</ul>

<div class="tab-content">
    <?php $i = 0; foreach ($childFields as $key => $field): $i++; ?>
    <div class="tab-pane <?= ($i == 1) ? 'active' : '' ?>" id="tab-<?= $field->getName(); ?>-<?= $key; ?>"><?= $field->render(); ?></div>
    <?php endforeach; ?>
</div>
