<ul class="nav nav-tabs">
    <?php foreach ($children as $key => $field): ?>
    <li data-toggle="tab" class="<?= ($key == 0) ? 'active' : '' ?>"><a href="#tab-<?= $field->getName(); ?>-<?= $key; ?>"><?= $field->getLabel(); ?></a></li>
    <?php endforeach; ?>
</ul>

<div class="tab-content">
    <?php foreach ($children as $key => $field): ?>
    <div class="tab-pane fade <?= ($key == 0) ? 'active' : '' ?>" id="tab-<?= $field->getName(); ?>-<?= $key; ?>"><?= $field; ?></div>
    <?php endforeach; ?>
</div>